### ISSUE TITLE
Multi-Instance Deployment - Dev to Test, then Test to Pre-Prod in .env

### ISSUE THREAD

**Issue by jayakumarss** [bmoers/sn-cicd-example#3]
Hello, I have 3 instances in place (DEV, TEST, and PREPROD)
currently I have the solution configured and works perfectly fine between DEV and TEST

I am trying to configure the end to end pipeline where the code moves from DEV to TEST at first, and then move the code from Test to PREPROD.

I have met all the pre-requisites already on all instances and I am also using the latest code base you have. As I am inspecting the .env properties files I am not able to get this working to achieve deployment for more than 1 environment as stated earlier.

 ---- Master Environment Mapping ---- 
use below settings to hard-link a development environment to a production environment (master)

if enabled, the 'git' information in the 'run' request from ServiceNow is not required.
set this to 'true' to only allow to checkout from master like specified below

CICD_GIT_STRICT_MASTER=true

default git master source (can be dangerous if you have multiple purpose instances. eg. IT and Finance)
#CICD_GIT_MASTER_SOURCE=dev123.service-now.com

master source definition CICD_GIT_MASTER_SOURCE_[INSTANCENAME] (instance short name)
this reads: if source is 'development.service-now.com', use 'prod.service-now.com' as the master

CICD_GIT_MASTER_SOURCE_DEVELOPMENT=dev123.service-now.com
CICD_GIT_MASTER_SOURCE_TESTING=test123.service-now.com
#CICD_GIT_MASTER_SOURCE_PREPROD=

---- Deployment Environment Mapping ---- 
use below settings to hard-link a source environment to a target environment
if enabled, the 'target' information in the 'run' request from ServiceNow is not required.

set this to 'true' to only deploy according to the below target definition
CICD_CD_STRICT_DEPLOYMENT=true

default deployment target (can be dangerous if you have multiple purpose instances. eg. IT and Finance)

#CICD_CD_DEPLOYMENT_TARGET=test123

deployment target definition
CICD_CD_DEPLOYMENT_TARGET_test123=test123.service-now.com
CICD_CD_DEPLOYMENT_TARGET_preprod123=preprod123.service-now.com
#CICD_CD_DEPLOYMENT_TARGET_PREPRODINSTANCE=company.service-now.com

Can you please let me know how I can get this to work?

**Comment by nadimrizk83** [comment]
I figured out the configuration for multi-deployment - I had my mappings mixed up and not well defined between source and deployment target - The below is the updated configuration which worked for me between the 3 instances: DEV, TEST, and PREPROD - Now I am able to deploy using the below configuration from DEV to TEST, and then move the code from TEST to PREPROD.

---- Master Environment Mapping ----
use below settings to hard-link a development environment to a production environment (master)

if enabled, the 'git' information in the 'run' request from ServiceNow is not required.
set this to 'true' to only allow to checkout from master like specified below

CICD_GIT_STRICT_MASTER=true

default git master source (can be dangerous if you have multiple purpose instances. eg. IT and Finance)
#CICD_GIT_MASTER_SOURCE=dev123.service-now.com

master source definition CICD_GIT_MASTER_SOURCE_[INSTANCENAME] (instance short name)
this reads: if source is 'development.service-now.com', use 'prod.service-now.com' as the master

CICD_GIT_MASTER_SOURCE_dev123=dev123.service-now.com
CICD_GIT_MASTER_SOURCE_test123=test123.service-now.com
#CICD_GIT_MASTER_SOURCE_PREPROD=

---- Deployment Environment Mapping ----
use below settings to hard-link a source environment to a target environment
if enabled, the 'target' information in the 'run' request from ServiceNow is not required.

set this to 'true' to only deploy according to the below target definition
CICD_CD_STRICT_DEPLOYMENT=true

default deployment target (can be dangerous if you have multiple purpose instances. eg. IT and Finance)

#CICD_CD_DEPLOYMENT_TARGET=test123

deployment target definition
CICD_CD_DEPLOYMENT_TARGET_dev123=test123.service-now.com
CICD_CD_DEPLOYMENT_TARGET_test123=preprod123.service-now.com
#CICD_CD_DEPLOYMENT_TARGET_PREPRODINSTANCE=company.service-now.com

**Comment by jayakumarss** [comment]
I figured out the configuration for multi-deployment - I had my mappings mixed up and not well defined between source and deployment target - The below is the updated configuration which worked for me between the 3 instances: DEV, TEST, and PREPROD - Now I am able to deploy using the below configuration from DEV to TEST, and then move the code from TEST to PREPROD.

---- Master Environment Mapping ----
use below settings to hard-link a development environment to a production environment (master)

if enabled, the 'git' information in the 'run' request from ServiceNow is not required.
set this to 'true' to only allow to checkout from master like specified below

CICD_GIT_STRICT_MASTER=true

default git master source (can be dangerous if you have multiple purpose instances. eg. IT and Finance)
#CICD_GIT_MASTER_SOURCE=dev123.service-now.com

master source definition CICD_GIT_MASTER_SOURCE_[INSTANCENAME] (instance short name)
this reads: if source is 'development.service-now.com', use 'prod.service-now.com' as the master

CICD_GIT_MASTER_SOURCE_dev123=dev123.service-now.com
CICD_GIT_MASTER_SOURCE_test123=test123.service-now.com
#CICD_GIT_MASTER_SOURCE_PREPROD=

---- Deployment Environment Mapping ----
use below settings to hard-link a source environment to a target environment
if enabled, the 'target' information in the 'run' request from ServiceNow is not required.

set this to 'true' to only deploy according to the below target definition
CICD_CD_STRICT_DEPLOYMENT=true

default deployment target (can be dangerous if you have multiple purpose instances. eg. IT and Finance)

#CICD_CD_DEPLOYMENT_TARGET=test123

deployment target definition
CICD_CD_DEPLOYMENT_TARGET_dev123=test123.service-now.com
CICD_CD_DEPLOYMENT_TARGET_test123=preprod123.service-now.com
#CICD_CD_DEPLOYMENT_TARGET_PREPRODINSTANCE=company.service-now.com

**Comment by bmoers** [comment]
closing as resolved
